apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gslb
  name: gslb
  namespace: gaia-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gslb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gslb
    spec:
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          env:
            - name: ACCESS_SERVICE_NAME
              value: access
            - name: ACCESS_SERVICE_DEFAULT_IP
              value: 124.223.205.137
          image: lmxia/gslb:v1
          imagePullPolicy: IfNotPresent
          name: gslb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
              readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeName: clo-glo-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: gaia
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: Corefile
                path: Corefile
            name: gslb
          name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gslb
    component: gslb
  name: gslb
  namespace: gaia-system
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: udp
      nodePort: 32347
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: crossdns
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
data:
  Corefile: |
    arservice.cloud:53 {
        crossdns
        errors
        health
        ready
    }
kind: ConfigMap
metadata:
  labels:
    app: gslb
    component: gslb
  name: gslb
  namespace: gaia-system